name: Deploy to Docker Hub and Render

on:
  push:
    branches:
      - main
    
jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for linux/amd64
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/clothing-bin-locator:latest

    - name: Trigger redeployment on Render
      if: success()
      run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
