name: Deploy to Docker Hub and Render

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Set Environment Variables and run npm build
            - name: Set Environment Variables and build
              env:
                  KAKAO_APP_JS_KEY: ${{ secrets.KAKAO_APP_JS_KEY }}
                  KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
                  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
                  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
                  RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
                  RDS_PORT: ${{ secrets.RDS_PORT }}
                  RDS_HOST: ${{ secrets.RDS_HOST }}
              run: |
                  npm install
                  npm run build

            # Build Docker image
            - name: Build Docker image
              run: |
                  docker build \
                    --build-arg KAKAO_APP_JS_KEY='${KAKAO_APP_JS_KEY}' \
                    --build-arg KAKAO_REST_API_KEY='${KAKAO_REST_API_KEY}' \
                    --build-arg RDS_USERNAME='${RDS_USERNAME}' \
                    --build-arg RDS_PASSWORD='${RDS_PASSWORD}' \
                    --build-arg RDS_DATABASE='${RDS_DATABASE}' \
                    --build-arg RDS_PORT='${RDS_PORT}' \
                    --build-arg RDS_HOST='${RDS_HOST}' \
                    -t ${{ secrets.DOCKER_USERNAME }}/clothing-bin-locator:latest \
                    .

            # Push Docker image
            - name: Push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/clothing-bin-locator:latest

            - name: Trigger redeployment on Render
              if: success()
              run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
